CREATE TABLE INT_LOCK (
    LOCK_KEY VARCHAR(36) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    CLIENT_ID VARCHAR(36),
    CREATED_DATE TIMESTAMP NOT NULL,
    CONSTRAINT INT_LOCK_PK PRIMARY KEY (LOCK_KEY, REGION)
);

CREATE INDEX INT_LOCK_IX1
    ON INT_LOCK (CREATED_DATE);